name: multi_currency_finance
description: "An app to manage finances involving multiple currencies"
publish_to: 'none'
version: 0.4.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
